"""Loads sample data + KB embeddings into memory once at startup.

If `data/kb_embeddings.npy` is missing or older than `kb_articles.json`, the
loader will compute embeddings on the fly using
AZURE_OPENAI_EMBEDDING_DEPLOYMENT and cache them to disk. In the committed
repo this file is regenerated by `data/generate_sample_data.py`.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "data"


@dataclass
class AppData:
    customers: list[dict[str, Any]] = field(default_factory=list)
    orders: list[dict[str, Any]] = field(default_factory=list)
    products: list[dict[str, Any]] = field(default_factory=list)
    warranty_terms: list[dict[str, Any]] = field(default_factory=list)
    kb_articles: list[dict[str, Any]] = field(default_factory=list)
    kb_embeddings: np.ndarray = field(default_factory=lambda: np.zeros((0, 1536), dtype=np.float32))

    # Mutable runtime state (lost on restart unless persisted externally).
    tickets: list[dict[str, Any]] = field(default_factory=list)
    returns: list[dict[str, Any]] = field(default_factory=list)

    # Lookup helpers (built once)
    customers_by_email: dict[str, dict[str, Any]] = field(default_factory=dict)
    customers_by_id: dict[int, dict[str, Any]] = field(default_factory=dict)
    orders_by_id: dict[int, dict[str, Any]] = field(default_factory=dict)
    products_by_sku: dict[str, dict[str, Any]] = field(default_factory=dict)
    warranty_by_category: dict[str, dict[str, Any]] = field(default_factory=dict)


def _load_json(name: str, default: Any) -> Any:
    path = DATA_DIR / name
    if not path.exists():
        return default
    return json.loads(path.read_text())


async def _ensure_kb_embeddings(articles: list[dict[str, Any]]) -> np.ndarray:
    npy_path = DATA_DIR / "kb_embeddings.npy"
    json_path = DATA_DIR / "kb_articles.json"
    if npy_path.exists() and (not json_path.exists() or npy_path.stat().st_mtime >= json_path.stat().st_mtime):
        arr = np.load(npy_path)
        if arr.shape[0] == len(articles):
            return arr.astype(np.float32)
        logger.warning("kb_embeddings.npy stale (rows=%d, articles=%d) — recomputing", arr.shape[0], len(articles))

    if not articles:
        return np.zeros((0, 1536), dtype=np.float32)

    logger.info("Computing KB embeddings on startup (%d articles)…", len(articles))
    try:
        from openai import AsyncAzureOpenAI
        from azure.identity.aio import DefaultAzureCredential, get_bearer_token_provider

        credential = DefaultAzureCredential()
        token_provider = get_bearer_token_provider(credential, "https://cognitiveservices.azure.com/.default")
        endpoint = os.environ["AZURE_OPENAI_ENDPOINT"].rstrip("/")
        deployment = os.getenv("AZURE_OPENAI_EMBEDDING_DEPLOYMENT", "text-embedding-3-small")

        client = AsyncAzureOpenAI(
            azure_endpoint=endpoint,
            azure_ad_token_provider=token_provider,
            api_version="2024-10-21",
        )
        try:
            texts = [f"{a.get('title', '')}\n\n{a.get('content', '')}" for a in articles]
            # Hard timeout so an unhealthy AOAI / IMDS never blocks app startup.
            resp = await asyncio.wait_for(
                client.embeddings.create(model=deployment, input=texts),
                timeout=20.0,
            )
            arr = np.array([d.embedding for d in resp.data], dtype=np.float32)
            try:
                np.save(npy_path, arr)
                logger.info("Saved %s (shape=%s)", npy_path, arr.shape)
            except OSError as exc:
                logger.warning("Could not persist kb_embeddings.npy: %s", exc)
            return arr
        finally:
            await client.close()
            await credential.close()
    except Exception:
        logger.exception(
            "Failed to compute KB embeddings — continuing with zeros. "
            "Help-center search will be degraded until embeddings are available."
        )
        return np.zeros((len(articles), 1536), dtype=np.float32)


async def load_all() -> AppData:
    """Load all static data + ensure embeddings are available."""
    customers = _load_json("customers.json", [])
    orders = _load_json("orders.json", [])
    products = _load_json("products.json", [])
    warranty_terms = _load_json("warranty_terms.json", [])
    kb_articles = _load_json("kb_articles.json", [])

    kb_embeddings = await _ensure_kb_embeddings(kb_articles)

    data = AppData(
        customers=customers,
        orders=orders,
        products=products,
        warranty_terms=warranty_terms,
        kb_articles=kb_articles,
        kb_embeddings=kb_embeddings,
    )
    data.customers_by_email = {c["email"].lower(): c for c in customers if c.get("email")}
    data.customers_by_id = {c["customer_id"]: c for c in customers if "customer_id" in c}
    data.orders_by_id = {o["order_id"]: o for o in orders if "order_id" in o}
    data.products_by_sku = {p["sku"]: p for p in products if p.get("sku")}
    data.warranty_by_category = {w["category"].lower(): w for w in warranty_terms if w.get("category")}
    logger.info(
        "Loaded data: %d customers, %d orders, %d products, %d kb articles",
        len(customers), len(orders), len(products), len(kb_articles),
    )
    set_app_data(data)
    return data


# ---------------------------------------------------------------------------
# Module-level singleton: tools call get_app_data() to access loaded data.
# This is simpler and more reliable than threading runtime.context through
# every tool when context_schema is not configured on the agent.
# ---------------------------------------------------------------------------
_APP_DATA: AppData | None = None


def set_app_data(data: AppData) -> None:
    global _APP_DATA
    _APP_DATA = data


def get_app_data() -> AppData | None:
    return _APP_DATA
